#!/bin/sh /etc/rc.common

START=95
STOP=15
USE_PROCD=1

start_service() {
	/usr/sbin/option-wan apply
}

stop_service() {
	/usr/sbin/option-wan clear
}

reload_service() {
	/usr/sbin/option-wan apply
}

service_triggers() {
	procd_add_reload_trigger option_wan network
}

